services:
  - type: web
    name: codex
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: <توکن_ربات_اینجا_بزار>
      - key: WEBHOOK_URL
        value: https://codex-4zmj.onrender.com/webhook
